# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('delta_object', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[(b'blue', b'Blue'), (b'red', b'Red'), (b'green', b'Green'), (b'yellow', b'Yellow')], default=b'blue', max_length=10)),
                ('tag', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[(b'blue', b'Blue'), (b'red', b'Red'), (b'green', b'Green'), (b'yellow', b'Yellow')], default=b'blue', max_length=10)),
                ('public', models.BooleanField(default=False)),
                ('notebook_logo', models.FileField(blank=True, upload_to=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('notebook', models.ManyToManyField(to='vbook.Notebook')),
                ('tag', models.ManyToManyField(to='vbook.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbook.Notebook'),
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbook.URL'),
        ),
    ]
