# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbook', '0005_auto_20161014_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
